/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Decimal = string;
export interface InstantiateMsg {
  box_price?: Uint128 | null;
  denom?: string | null;
  distribution?: WeightInfo[] | null;
  treasury: string;
  worker?: string | null;
}
export interface WeightInfo {
  box_rewards: Uint128;
  weight: Decimal;
}
export type ExecuteMsg = {
  buy: {};
} | {
  open: {};
} | {
  claim: {};
} | {
  send: {
    amount: Uint128;
    recipient: string;
  };
} | {
  accept_admin_role: {};
} | {
  update_config: {
    admin?: string | null;
    box_price?: Uint128 | null;
    denom?: string | null;
    distribution?: WeightInfo[] | null;
    worker?: string | null;
  };
} | {
  lock: {};
} | {
  unlock: {};
};
export type QueryMsg = {
  query_config: {};
} | {
  query_box_stats: {};
} | {
  query_user: {
    address: string;
  };
} | {
  query_user_list: {
    limit?: number | null;
    start_after?: string | null;
  };
};
export interface MigrateMsg {
  version: string;
}
export interface BoxStats {
  opened: OpeningInfo[];
  sold: Uint128;
}
export interface OpeningInfo {
  box_rewards: Uint128;
  opened: Uint128;
}
export type Addr = string;
export interface Config {
  admin: Addr;
  box_price: Uint128;
  denom: string;
  distribution: WeightInfo[];
  treasury: Addr;
  worker?: Addr | null;
}
export interface UserInfo {
  bought: Uint128;
  boxes: Uint128;
  opened: OpeningInfo[];
  opening_date: number;
  received: Uint128;
  rewards: Uint128;
  sent: Uint128;
}
export type ArrayOfQueryUserListResponseItem = QueryUserListResponseItem[];
export interface QueryUserListResponseItem {
  address: Addr;
  info: UserInfo;
}