/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Decimal = string;
export interface InstantiateMsg {
  box_list_length?: number | null;
  box_price?: Uint128 | null;
  price_and_weight_list?: [Uint128, Decimal][] | null;
  proxy?: string | null;
  worker?: string | null;
}
export type ExecuteMsg = {
  nois_receive: {
    callback: NoisCallback;
  };
} | {
  accept_admin_role: {};
} | {
  update_config: {
    admin?: string | null;
    box_list_length?: number | null;
    box_price?: Uint128 | null;
    price_and_weight_list?: [Uint128, Decimal][] | null;
    proxy?: string | null;
    worker?: string | null;
  };
} | {
  request_box_list: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type HexBinary = string;
export interface NoisCallback {
  job_id: string;
  published: Timestamp;
  randomness: HexBinary;
}
export type QueryMsg = {
  query_config: {};
} | {
  query_box_list: {};
};
export interface MigrateMsg {
  version: string;
}
export interface BoxList {
  price_list: Uint128[];
  update_date: number;
}
export type Addr = string;
export interface Config {
  admin: Addr;
  box_list_length: number;
  box_price: Uint128;
  price_and_weight_list: [Uint128, Decimal][];
  proxy?: Addr | null;
  worker?: Addr | null;
}