/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Uint128, Decimal, InstantiateMsg, WeightInfo, ExecuteMsg, NftInfoForString, QueryMsg, MigrateMsg, Addr, Balance, NftInfoForAddr, BoxStats, OpeningInfo, Config, UserInfo, ArrayOfQueryUserListResponseItem, QueryUserListResponseItem } from "./Platform.types";
export interface PlatformMsg {
  contractAddress: string;
  sender: string;
  buy: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  open: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  claim: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  send: ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  acceptAdminRole: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  deposit: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  depositNft: ({
    nftInfoList
  }: {
    nftInfoList: NftInfoForString[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateConfig: ({
    admin,
    boxPrice,
    denom,
    distribution,
    worker
  }: {
    admin?: string;
    boxPrice?: Uint128;
    denom?: string;
    distribution?: WeightInfo[];
    worker?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  lock: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unlock: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  withdraw: ({
    amount
  }: {
    amount: Uint128;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  withdrawNft: ({
    nftInfoList
  }: {
    nftInfoList: NftInfoForString[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateNftPrice: ({
    nftInfoList
  }: {
    nftInfoList: NftInfoForString[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class PlatformMsgComposer implements PlatformMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.buy = this.buy.bind(this);
    this.open = this.open.bind(this);
    this.claim = this.claim.bind(this);
    this.send = this.send.bind(this);
    this.acceptAdminRole = this.acceptAdminRole.bind(this);
    this.deposit = this.deposit.bind(this);
    this.depositNft = this.depositNft.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.lock = this.lock.bind(this);
    this.unlock = this.unlock.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.withdrawNft = this.withdrawNft.bind(this);
    this.updateNftPrice = this.updateNftPrice.bind(this);
  }
  buy = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          buy: {}
        })),
        funds: _funds
      })
    };
  };
  open = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          open: {}
        })),
        funds: _funds
      })
    };
  };
  claim = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          claim: {}
        })),
        funds: _funds
      })
    };
  };
  send = ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          send: {
            amount,
            recipient
          }
        })),
        funds: _funds
      })
    };
  };
  acceptAdminRole = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          accept_admin_role: {}
        })),
        funds: _funds
      })
    };
  };
  deposit = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          deposit: {}
        })),
        funds: _funds
      })
    };
  };
  depositNft = ({
    nftInfoList
  }: {
    nftInfoList: NftInfoForString[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          deposit_nft: {
            nft_info_list: nftInfoList
          }
        })),
        funds: _funds
      })
    };
  };
  updateConfig = ({
    admin,
    boxPrice,
    denom,
    distribution,
    worker
  }: {
    admin?: string;
    boxPrice?: Uint128;
    denom?: string;
    distribution?: WeightInfo[];
    worker?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_config: {
            admin,
            box_price: boxPrice,
            denom,
            distribution,
            worker
          }
        })),
        funds: _funds
      })
    };
  };
  lock = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          lock: {}
        })),
        funds: _funds
      })
    };
  };
  unlock = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unlock: {}
        })),
        funds: _funds
      })
    };
  };
  withdraw = ({
    amount
  }: {
    amount: Uint128;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          withdraw: {
            amount
          }
        })),
        funds: _funds
      })
    };
  };
  withdrawNft = ({
    nftInfoList
  }: {
    nftInfoList: NftInfoForString[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          withdraw_nft: {
            nft_info_list: nftInfoList
          }
        })),
        funds: _funds
      })
    };
  };
  updateNftPrice = ({
    nftInfoList
  }: {
    nftInfoList: NftInfoForString[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_nft_price: {
            nft_info_list: nftInfoList
          }
        })),
        funds: _funds
      })
    };
  };
}